/**
 * CORE-P2-009H — components and variants end-to-end (ED-COMP-001,
 * ED-VARIANT-001/002; DD-DEC-010; DD-0019 §14.4, §32.3).
 *
 * **Visual certification is CI-only.** WSL2 headless screenshot
 * capture is broken on this dev box (verified in the Phase 1B close),
 * so this suite asserts DOM and sidecar state only; visual baselines
 * are generated by CI — the same split `visual-editor.spec.ts` uses.
 *
 * The flow certified here is the one a user can actually reach today:
 * multi-select on the canvas → **Create component** on the selection
 * toolbar → the capture commits as ONE undo step. The variant
 * *authoring* form (declaring axes) does not ship yet; its semantics
 * are unit-certified in
 * `packages/runtime/core/src/editor/__tests__/variants.test.ts` and
 * `variant-switch.test.ts`, and this file deliberately does not
 * pretend otherwise.
 */

import { expect, type Page, test } from "@playwright/test";

const EDITOR_URL = "/puck/editor?editor=1&collab=0";

async function openEditor(page: Page): Promise<void> {
	await page.goto(EDITOR_URL);
	await expect(page.getByTestId("ak-write-target")).toBeVisible({
		timeout: 90_000,
	});
}

/** Open the Layers rail module and its inner Layers tab. */
async function openLayersPanel(page: Page): Promise<void> {
	const railTab = page.locator("#ak-rail-tab-layer");
	await railTab.waitFor({ state: "attached", timeout: 30_000 });
	await railTab.click({ force: true });
	await expect(page.getByTestId("ak-module-layer")).toBeVisible({
		timeout: 10_000,
	});
	await page.getByTestId("ak-layer-tab-layers").click({ force: true });
	await expect(page.getByTestId("ak-layer-layers")).toBeVisible({
		timeout: 10_000,
	});
}

/**
 * Click a layer row. The tree is virtualized and the demo canvas
 * animates continuously, so scroll the row in and force the click —
 * the `visual-editor.spec.ts` precedent.
 */
async function clickLayerRow(
	page: Page,
	nodeId: string,
	modifiers?: { readonly ctrl: boolean },
): Promise<void> {
	const row = page.getByTestId(`ak-layer-select-${nodeId}`);
	await row.waitFor({ state: "attached", timeout: 15_000 });
	await expect(async () => {
		await row.evaluate((element) =>
			element.scrollIntoView({ block: "center", behavior: "instant" }),
		);
		await row.click({
			force: true,
			...(modifiers?.ctrl === true ? { modifiers: ["ControlOrMeta"] } : {}),
		});
		// Selection is announced on the `treeitem` ROW, not on the name
		// button: `aria-selected` is invalid on `button` (axe
		// `aria-allowed-attr`) and moved to the row in CORE-P4-003.
		await expect(
			page.getByTestId(`ak-layer-node-${nodeId}`),
		).toHaveAttribute("aria-selected", "true", { timeout: 2_000 });
	}).toPass({ timeout: 20_000 });
}

/** The first two top-level layer node ids in the demo document. */
async function topLevelNodeIds(page: Page): Promise<readonly string[]> {
	return page.evaluate(() =>
		[...document.querySelectorAll("[data-testid^='ak-layer-select-']")]
			.map((element) =>
				(element.getAttribute("data-testid") ?? "").replace(
					"ak-layer-select-",
					"",
				),
			)
			.filter((id) => id.length > 0),
	);
}

test.describe("components and variants (CORE-P2-009H)", () => {
	// The `/puck/editor` route's first compile under `next dev
	// --turbopack` takes 60–90 s on this box (documented in
	// playwright.config.ts).
	test.describe.configure({ timeout: 180_000 });

	test("the isolated component canvas stays hidden in page scope", async ({
		page,
	}) => {
		const pageErrors: string[] = [];
		page.on("pageerror", (error) => pageErrors.push(String(error)));
		await openEditor(page);
		await openLayersPanel(page);

		// Page scope must not render the component canvas (§10.6).
		await expect(page.getByTestId("ak-component-canvas")).toHaveCount(0);
		expect(pageErrors).toEqual([]);
	});

	test("multi-select exposes Create component on the selection toolbar", async ({
		page,
	}) => {
		const pageErrors: string[] = [];
		page.on("pageerror", (error) => pageErrors.push(String(error)));
		await openEditor(page);
		await openLayersPanel(page);

		const ids = await topLevelNodeIds(page);
		test.skip(ids.length < 2, "demo document has fewer than two layer rows");

		await clickLayerRow(page, ids[0] as string);
		await clickLayerRow(page, ids[1] as string, { ctrl: true });

		// The toolbar lives in the canvas iframe's overlay root.
		const frame = page.frameLocator("iframe").first();
		const toolbar = frame.locator("[data-ak-selection-toolbar]");
		await expect(toolbar).toBeVisible({ timeout: 15_000 });
		await expect(
			toolbar.locator("[data-ak-toolbar-action='create-component']"),
		).toBeVisible();
		expect(pageErrors).toEqual([]);
	});

	test("Create component captures the selection in one undo step", async ({
		page,
	}) => {
		const pageErrors: string[] = [];
		page.on("pageerror", (error) => pageErrors.push(String(error)));
		await openEditor(page);
		await openLayersPanel(page);

		const ids = await topLevelNodeIds(page);
		test.skip(ids.length < 2, "demo document has fewer than two layer rows");
		const before = ids.length;

		await clickLayerRow(page, ids[0] as string);
		await clickLayerRow(page, ids[1] as string, { ctrl: true });

		const frame = page.frameLocator("iframe").first();
		await frame
			.locator("[data-ak-toolbar-action='create-component']")
			.click({ force: true });

		// Two nodes leave the page, one instance replaces them.
		await expect(async () => {
			const after = await topLevelNodeIds(page);
			expect(after.length).toBe(before - 1);
		}).toPass({ timeout: 20_000 });

		// §10.5 single-intent history: ONE undo restores both nodes.
		// Use the chrome's Undo button, not a keyboard shortcut: after
		// clicking a toolbar action focus sits inside the canvas iframe,
		// where Ctrl+Z never reaches Puck's history (the
		// `visual-editor.spec.ts` precedent).
		await page.getByRole("button", { name: /undo/i }).click();
		await expect(async () => {
			const restored = await topLevelNodeIds(page);
			expect(restored.length).toBe(before);
		}).toPass({ timeout: 20_000 });

		expect(pageErrors).toEqual([]);
	});
});
