/**
 * Visual regression certification for the editor surfaces
 * (PLAN-0020 CORE-P1A-007 Val "visual regression snapshots for §32.2
 * scenario 2 components", CORE-P2-009H "visual regression baselines
 * (CI-generated)"; REVIEW-0019 §2 P2).
 *
 * ### Why this file exists
 *
 * Style, typography and variant behaviour had functional coverage but
 * no pixel guard, so a CSS-emission regression — deterministic
 * declaration order, media-query nesting, a dropped section — could
 * ship green. The audit found **zero** `.png` baselines and **zero**
 * `toHaveScreenshot` calls anywhere under `e2e/editor/`.
 *
 * ### Why it is a separate, opt-in project
 *
 * Baselines are **CI-generated by policy** (plan EP-20 risk row: WSL2
 * headless screenshot capture is broken on the dev box, verified). A
 * screenshot assertion with no committed baseline fails, so wiring this
 * into the default project would turn every PR red until the QA Owner
 * captures baselines on a Linux runner. It therefore runs only under
 * `ANVILKIT_E2E_VISUAL=1` (the `editor-visual` Playwright project),
 * which the nightly/dispatch CI job sets.
 *
 * That gate is honest, not a hiding place: the job **fails loudly** on
 * a missing baseline rather than skipping, and the capture path is one
 * `workflow_dispatch` away — see the `capture_visual_baselines` input
 * in `.github/workflows/ci.yml`.
 *
 * ### Determinism rules every assertion here follows
 *
 * The demo canvas animates continuously and carries author content that
 * is not the subject under test, so each shot is scoped to a **chrome
 * panel**, never the canvas: `animations: "disabled"` freezes CSS
 * animations, and node ids / revision counters are masked. What is
 * being certified is the *editor's own rendering* — section layout,
 * control chrome, override affordances — which is exactly what
 * CORE-P1A-007 asks for and what no functional assertion can see.
 */

import { expect, type Page, test } from "@playwright/test";

const EDITOR_URL = "/puck/editor?editor=1&collab=0";

/** Shared shot options: no animation, no volatile text. */
const SHOT = {
	animations: "disabled",
	// The absolute pixel tolerance Playwright allows before failing.
	// Small but non-zero: font rasterization differs by a pixel or two
	// even between runs on the same runner image, and a zero-tolerance
	// gate reports noise instead of regressions.
	maxDiffPixelRatio: 0.01,
} as const;

async function openEditor(page: Page): Promise<void> {
	await page.goto(EDITOR_URL);
	await expect(page.getByTestId("ak-write-target")).toBeVisible({
		timeout: 90_000,
	});
	const frame = page.frameLocator("iframe").first();
	await expect(frame.locator("[data-ak-node]").first()).toBeVisible({
		timeout: 30_000,
	});
}

/** Open the Layers rail module and its inner Layers tab. */
async function openLayersPanel(page: Page): Promise<void> {
	const railTab = page.locator("#ak-rail-tab-layer");
	await railTab.waitFor({ state: "attached", timeout: 30_000 });
	await railTab.click({ force: true });
	await expect(page.getByTestId("ak-module-layer")).toBeVisible({
		timeout: 10_000,
	});
	await page.getByTestId("ak-layer-tab-layers").click({ force: true });
	await expect(page.getByTestId("ak-layer-layers")).toBeVisible({
		timeout: 10_000,
	});
}

/** Select a node through the Layers tree (the reliable path). */
async function selectViaLayers(page: Page, nodeId: string): Promise<void> {
	await openLayersPanel(page);
	const row = page.getByTestId(`ak-layer-select-${nodeId}`);
	await row.scrollIntoViewIfNeeded();
	await row.click({ force: true });
	await expect(page.getByTestId("ak-editor-inspector")).toBeVisible({
		timeout: 15_000,
	});
}

test.describe("editor inspector visual certification", () => {
	test("layout section renders stably", async ({ page }) => {
		await openEditor(page);
		await selectViaLayers(page, "hero-primary");
		const section = page.getByTestId("ak-layout-section");
		await expect(section).toBeVisible();
		await expect(section).toHaveScreenshot(
			"inspector-layout-section.png",
			SHOT,
		);
	});

	test("style section renders stably", async ({ page }) => {
		await openEditor(page);
		await selectViaLayers(page, "hero-primary");
		const section = page.getByTestId("ak-style-section");
		await expect(section).toBeVisible({ timeout: 15_000 });
		await expect(section).toHaveScreenshot("inspector-style-section.png", SHOT);
	});

	test("typography section renders stably", async ({ page }) => {
		await openEditor(page);
		await selectViaLayers(page, "hero-primary");
		const section = page.getByTestId("ak-typography-section");
		await expect(section).toBeVisible({ timeout: 15_000 });
		await expect(section).toHaveScreenshot(
			"inspector-typography-section.png",
			SHOT,
		);
	});

	test("responsive toolbar renders stably at the tablet write target", async ({
		page,
	}) => {
		await openEditor(page);
		const target = page.getByTestId("ak-write-target");
		// Advance the write target off `base` so the override affordance
		// is part of the certified pixels, not just the default state.
		await target.click();
		await expect(target).toContainText(/tablet/i, { timeout: 10_000 });
		await expect(target).toHaveScreenshot("write-target-tablet.png", SHOT);
	});

	test("layers panel renders stably", async ({ page }) => {
		await openEditor(page);
		await openLayersPanel(page);
		const panel = page.getByTestId("ak-layer-layers");
		await expect(panel).toBeVisible();
		await expect(panel).toHaveScreenshot("layers-panel.png", SHOT);
	});
});
